services:
  - type: web
    name: dash-color-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app.server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 